# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 170b980dc7a53f2d95385aa57dbe984da4aa6b64d8627bf3c1d12e4209dfd1da45e0d78efa3e3123499ee9df0d73c341830b259eaa39f9232822ac4dcd503ecb

test:
  secret_key_base: ad2b4f79195c6695eb83d7a2f3ae041a8fd514475c65ecea399c54886cd4d43ad19a611da529031e73745c83b5cf26574c4dd93ded958df9dbbe2435f1ea4c82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
